export const YEARS = Array.from({ length: 30 }, (_, i) => {
  const year = (new Date().getFullYear() - i).toString();
  return { label: year, value: year };
});

export const CAR_MAKES = [
  { label: 'Acura', value: 'Acura' },
  { label: 'Alfa Romeo', value: 'Alfa Romeo' },
  { label: 'Audi', value: 'Audi' },
  { label: 'BMW', value: 'BMW' },
  { label: 'Buick', value: 'Buick' },
  { label: 'Cadillac', value: 'Cadillac' },
  { label: 'Chevrolet', value: 'Chevrolet' },
  { label: 'Chrysler', value: 'Chrysler' },
  { label: 'Dodge', value: 'Dodge' },
  { label: 'Ford', value: 'Ford' },
  { label: 'Genesis', value: 'Genesis' },
  { label: 'GMC', value: 'GMC' },
  { label: 'Honda', value: 'Honda' },
  { label: 'Hyundai', value: 'Hyundai' },
  { label: 'Infiniti', value: 'Infiniti' },
  { label: 'Jaguar', value: 'Jaguar' },
  { label: 'Jeep', value: 'Jeep' },
  { label: 'Kia', value: 'Kia' },
  { label: 'Land Rover', value: 'Land Rover' },
  { label: 'Lexus', value: 'Lexus' },
  { label: 'Lincoln', value: 'Lincoln' },
  { label: 'Mazda', value: 'Mazda' },
  { label: 'Mercedes-Benz', value: 'Mercedes-Benz' },
  { label: 'Mini', value: 'Mini' },
  { label: 'Mitsubishi', value: 'Mitsubishi' },
  { label: 'Nissan', value: 'Nissan' },
  { label: 'Porsche', value: 'Porsche' },
  { label: 'Ram', value: 'Ram' },
  { label: 'Subaru', value: 'Subaru' },
  { label: 'Tesla', value: 'Tesla' },
  { label: 'Toyota', value: 'Toyota' },
  { label: 'Volkswagen', value: 'Volkswagen' },
  { label: 'Volvo', value: 'Volvo' },
];

// Canada ke popular models per company
export const CAR_MODELS: Record<string, { label: string; value: string }[]> = {
  Acura: [
    { label: 'ILX', value: 'ILX' },
    { label: 'Integra', value: 'Integra' },
    { label: 'MDX', value: 'MDX' },
    { label: 'RDX', value: 'RDX' },
    { label: 'TLX', value: 'TLX' },
  ],
  'Alfa Romeo': [
    { label: 'Giulia', value: 'Giulia' },
    { label: 'Stelvio', value: 'Stelvio' },
    { label: 'Tonale', value: 'Tonale' },
  ],
  Audi: [
    { label: 'A3', value: 'A3' },
    { label: 'A4', value: 'A4' },
    { label: 'A5', value: 'A5' },
    { label: 'A6', value: 'A6' },
    { label: 'A7', value: 'A7' },
    { label: 'Q3', value: 'Q3' },
    { label: 'Q5', value: 'Q5' },
    { label: 'Q7', value: 'Q7' },
    { label: 'Q8', value: 'Q8' },
    { label: 'e-tron', value: 'e-tron' },
  ],
  BMW: [
    { label: '2 Series', value: '2 Series' },
    { label: '3 Series', value: '3 Series' },
    { label: '4 Series', value: '4 Series' },
    { label: '5 Series', value: '5 Series' },
    { label: '7 Series', value: '7 Series' },
    { label: 'X1', value: 'X1' },
    { label: 'X3', value: 'X3' },
    { label: 'X5', value: 'X5' },
    { label: 'X7', value: 'X7' },
    { label: 'i4', value: 'i4' },
  ],
  Buick: [
    { label: 'Enclave', value: 'Enclave' },
    { label: 'Encore', value: 'Encore' },
    { label: 'Envision', value: 'Envision' },
  ],
  Cadillac: [
    { label: 'CT4', value: 'CT4' },
    { label: 'CT5', value: 'CT5' },
    { label: 'Escalade', value: 'Escalade' },
    { label: 'XT4', value: 'XT4' },
    { label: 'XT5', value: 'XT5' },
  ],
  Chevrolet: [
    { label: 'Blazer', value: 'Blazer' },
    { label: 'Camaro', value: 'Camaro' },
    { label: 'Colorado', value: 'Colorado' },
    { label: 'Corvette', value: 'Corvette' },
    { label: 'Equinox', value: 'Equinox' },
    { label: 'Silverado 1500', value: 'Silverado 1500' },
    { label: 'Suburban', value: 'Suburban' },
    { label: 'Tahoe', value: 'Tahoe' },
    { label: 'Traverse', value: 'Traverse' },
  ],
  Chrysler: [
    { label: '300', value: '300' },
    { label: 'Grand Caravan', value: 'Grand Caravan' },
    { label: 'Pacifica', value: 'Pacifica' },
  ],
  Dodge: [
    { label: 'Challenger', value: 'Challenger' },
    { label: 'Charger', value: 'Charger' },
    { label: 'Durango', value: 'Durango' },
    { label: 'Hornet', value: 'Hornet' },
  ],
  Ford: [
    { label: 'Bronco', value: 'Bronco' },
    { label: 'Edge', value: 'Edge' },
    { label: 'Escape', value: 'Escape' },
    { label: 'Expedition', value: 'Expedition' },
    { label: 'Explorer', value: 'Explorer' },
    { label: 'F-150', value: 'F-150' },
    { label: 'Mustang', value: 'Mustang' },
    { label: 'Ranger', value: 'Ranger' },
  ],
  Genesis: [
    { label: 'G70', value: 'G70' },
    { label: 'G80', value: 'G80' },
    { label: 'GV70', value: 'GV70' },
    { label: 'GV80', value: 'GV80' },
  ],
  GMC: [
    { label: 'Acadia', value: 'Acadia' },
    { label: 'Canyon', value: 'Canyon' },
    { label: 'Sierra 1500', value: 'Sierra 1500' },
    { label: 'Terrain', value: 'Terrain' },
    { label: 'Yukon', value: 'Yukon' },
  ],
  Honda: [
    { label: 'Accord', value: 'Accord' },
    { label: 'Civic', value: 'Civic' },
    { label: 'CR-V', value: 'CR-V' },
    { label: 'HR-V', value: 'HR-V' },
    { label: 'Odyssey', value: 'Odyssey' },
    { label: 'Passport', value: 'Passport' },
    { label: 'Pilot', value: 'Pilot' },
    { label: 'Ridgeline', value: 'Ridgeline' },
  ],
  Hyundai: [
    { label: 'Elantra', value: 'Elantra' },
    { label: 'Ioniq 5', value: 'Ioniq 5' },
    { label: 'Kona', value: 'Kona' },
    { label: 'Palisade', value: 'Palisade' },
    { label: 'Santa Fe', value: 'Santa Fe' },
    { label: 'Sonata', value: 'Sonata' },
    { label: 'Tucson', value: 'Tucson' },
  ],
  Infiniti: [
    { label: 'Q50', value: 'Q50' },
    { label: 'QX50', value: 'QX50' },
    { label: 'QX60', value: 'QX60' },
    { label: 'QX80', value: 'QX80' },
  ],
  Jaguar: [
    { label: 'E-Pace', value: 'E-Pace' },
    { label: 'F-Pace', value: 'F-Pace' },
    { label: 'F-Type', value: 'F-Type' },
  ],
  Jeep: [
    { label: 'Cherokee', value: 'Cherokee' },
    { label: 'Compass', value: 'Compass' },
    { label: 'Gladiator', value: 'Gladiator' },
    { label: 'Grand Cherokee', value: 'Grand Cherokee' },
    { label: 'Wrangler', value: 'Wrangler' },
  ],
  Kia: [
    { label: 'Carnival', value: 'Carnival' },
    { label: 'EV6', value: 'EV6' },
    { label: 'Forte', value: 'Forte' },
    { label: 'K5', value: 'K5' },
    { label: 'Sorento', value: 'Sorento' },
    { label: 'Sportage', value: 'Sportage' },
    { label: 'Telluride', value: 'Telluride' },
  ],
  'Land Rover': [
    { label: 'Defender', value: 'Defender' },
    { label: 'Discovery', value: 'Discovery' },
    { label: 'Range Rover', value: 'Range Rover' },
    { label: 'Range Rover Evoque', value: 'Range Rover Evoque' },
    { label: 'Range Rover Sport', value: 'Range Rover Sport' },
  ],
  Lexus: [
    { label: 'ES', value: 'ES' },
    { label: 'GX', value: 'GX' },
    { label: 'IS', value: 'IS' },
    { label: 'NX', value: 'NX' },
    { label: 'RX', value: 'RX' },
    { label: 'UX', value: 'UX' },
  ],
  Lincoln: [
    { label: 'Aviator', value: 'Aviator' },
    { label: 'Corsair', value: 'Corsair' },
    { label: 'Nautilus', value: 'Nautilus' },
    { label: 'Navigator', value: 'Navigator' },
  ],
  Mazda: [
    { label: 'CX-30', value: 'CX-30' },
    { label: 'CX-5', value: 'CX-5' },
    { label: 'CX-50', value: 'CX-50' },
    { label: 'CX-90', value: 'CX-90' },
    { label: 'Mazda3', value: 'Mazda3' },
  ],
  'Mercedes-Benz': [
    { label: 'A-Class', value: 'A-Class' },
    { label: 'C-Class', value: 'C-Class' },
    { label: 'E-Class', value: 'E-Class' },
    { label: 'S-Class', value: 'S-Class' },
    { label: 'GLA', value: 'GLA' },
    { label: 'GLB', value: 'GLB' },
    { label: 'GLC', value: 'GLC' },
    { label: 'GLE', value: 'GLE' },
    { label: 'GLS', value: 'GLS' },
  ],
  Mini: [
    { label: 'Clubman', value: 'Clubman' },
    { label: 'Cooper', value: 'Cooper' },
    { label: 'Countryman', value: 'Countryman' },
  ],
  Mitsubishi: [
    { label: 'Eclipse Cross', value: 'Eclipse Cross' },
    { label: 'Mirage', value: 'Mirage' },
    { label: 'Outlander', value: 'Outlander' },
    { label: 'RVR', value: 'RVR' },
  ],
  Nissan: [
    { label: 'Altima', value: 'Altima' },
    { label: 'Kicks', value: 'Kicks' },
    { label: 'Murano', value: 'Murano' },
    { label: 'Pathfinder', value: 'Pathfinder' },
    { label: 'Rogue', value: 'Rogue' },
    { label: 'Sentra', value: 'Sentra' },
    { label: 'Frontier', value: 'Frontier' },
  ],
  Porsche: [
    { label: '911', value: '911' },
    { label: 'Cayenne', value: 'Cayenne' },
    { label: 'Macan', value: 'Macan' },
    { label: 'Panamera', value: 'Panamera' },
    { label: 'Taycan', value: 'Taycan' },
  ],
  Ram: [
    { label: '1500', value: '1500' },
    { label: '2500', value: '2500' },
    { label: '3500', value: '3500' },
    { label: 'ProMaster', value: 'ProMaster' },
  ],
  Subaru: [
    { label: 'Crosstrek', value: 'Crosstrek' },
    { label: 'Forester', value: 'Forester' },
    { label: 'Impreza', value: 'Impreza' },
    { label: 'Outback', value: 'Outback' },
    { label: 'WRX', value: 'WRX' },
  ],
  Tesla: [
    { label: 'Model 3', value: 'Model 3' },
    { label: 'Model S', value: 'Model S' },
    { label: 'Model X', value: 'Model X' },
    { label: 'Model Y', value: 'Model Y' },
  ],
  Toyota: [
    { label: '4Runner', value: '4Runner' },
    { label: 'Camry', value: 'Camry' },
    { label: 'Corolla', value: 'Corolla' },
    { label: 'Highlander', value: 'Highlander' },
    { label: 'PRIUS', value: 'Prius' },
    { label: 'RAV4', value: 'RAV4' },
    { label: 'Sequoia', value: 'Sequoia' },
    { label: 'Sienna', value: 'Sienna' },
    { label: 'Tacoma', value: 'Tacoma' },
    { label: 'Tundra', value: 'Tundra' },
  ],
  Volkswagen: [
    { label: 'Atlas', value: 'Atlas' },
    { label: 'Golf', value: 'Golf' },
    { label: 'ID.4', value: 'ID.4' },
    { label: 'Jetta', value: 'Jetta' },
    { label: 'Taos', value: 'Taos' },
    { label: 'Tiguan', value: 'Tiguan' },
  ],
  Volvo: [
    { label: 'S60', value: 'S60' },
    { label: 'V60', value: 'V60' },
    { label: 'XC40', value: 'XC40' },
    { label: 'XC60', value: 'XC60' },
    { label: 'XC90', value: 'XC90' },
  ],
};