export const YEARS = Array.from({ length: 30 }, (_, i) => {
  const year = (new Date().getFullYear() - i).toString();
  return { label: year, value: year };
});

export const CAR_MAKES = [
  { label: 'Acura', value: 'Acura' },
  { label: 'Alfa Romeo', value: 'Alfa Romeo' },
  { label: 'Aston Martin', value: 'Aston Martin' },
  { label: 'Audi', value: 'Audi' },
  { label: 'Bentley', value: 'Bentley' },
  { label: 'BMW', value: 'BMW' },
  { label: 'Buick', value: 'Buick' },
  { label: 'Cadillac', value: 'Cadillac' },
  { label: 'Chevrolet', value: 'Chevrolet' },
  { label: 'Chrysler', value: 'Chrysler' },
  { label: 'Dodge', value: 'Dodge' },
  { label: 'Ferrari', value: 'Ferrari' },
  { label: 'Fiat', value: 'Fiat' },
  { label: 'Ford', value: 'Ford' },
  { label: 'Genesis', value: 'Genesis' },
  { label: 'GMC', value: 'GMC' },
  { label: 'Honda', value: 'Honda' },
  { label: 'Hyundai', value: 'Hyundai' },
  { label: 'Infiniti', value: 'Infiniti' },
  { label: 'Jaguar', value: 'Jaguar' },
  { label: 'Jeep', value: 'Jeep' },
  { label: 'Kia', value: 'Kia' },
  { label: 'Lamborghini', value: 'Lamborghini' },
  { label: 'Land Rover', value: 'Land Rover' },
  { label: 'Lexus', value: 'Lexus' },
  { label: 'Lincoln', value: 'Lincoln' },
  { label: 'Lucid', value: 'Lucid' },
  { label: 'Maserati', value: 'Maserati' },
  { label: 'Mazda', value: 'Mazda' },
  { label: 'McLaren', value: 'McLaren' },
  { label: 'Mercedes-Benz', value: 'Mercedes-Benz' },
  { label: 'Mini', value: 'Mini' },
  { label: 'Mitsubishi', value: 'Mitsubishi' },
  { label: 'Nissan', value: 'Nissan' },
  { label: 'Polestar', value: 'Polestar' },
  { label: 'Porsche', value: 'Porsche' },
  { label: 'Ram', value: 'Ram' },
  { label: 'Rivian', value: 'Rivian' },
  { label: 'Rolls-Royce', value: 'Rolls-Royce' },
  { label: 'Subaru', value: 'Subaru' },
  { label: 'Tesla', value: 'Tesla' },
  { label: 'Toyota', value: 'Toyota' },
  { label: 'Volkswagen', value: 'Volkswagen' },
  { label: 'Volvo', value: 'Volvo' },
  // Discontinued / Popular Used Brands in Canada
  { label: 'Pontiac', value: 'Pontiac' },
  { label: 'Saturn', value: 'Saturn' },
  { label: 'Scion', value: 'Scion' },
  { label: 'Smart', value: 'Smart' },
  { label: 'Suzuki', value: 'Suzuki' },
];